package View;


import Controller.PrestamoController;
import Model.Libro;
import Model.Usuario;
import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PrevisualizarPrestamo extends javax.swing.JFrame {
    

    private int idUsuario;
    private int idLibro;

    public PrevisualizarPrestamo(int idUsuario, int idLibro) {
        initComponents();
    setLocationRelativeTo(null);
    setTitle("Confirmar Préstamo");

    // 🔴 IMPORTANTE — SIN ESTO NADA FUNCIONA
    this.idUsuario = idUsuario;
    this.idLibro = idLibro;

    // Permite cerrar solo la ventana
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    PrestamoController controller = new PrestamoController();
    Model.Prestamo p = controller.obtenerPrevisualizacion(idUsuario, idLibro);

    if (p != null) {
        lblTitulo.setText(p.getTitulo());
        jSolicitanteField1.setText(p.getNombreSolicitante());
        jFechaSolitudField1.setText(String.valueOf(p.getFechaSolicitud()));
        jFechaDevolucionField1.setText(String.valueOf(p.getFechaDevolucion()));

        if (p.getImagen() != null && p.getImagen().length > 0) {
            ImageIcon icon = new ImageIcon(p.getImagen());
            Image img = icon.getImage().getScaledInstance(
                lblImagen.getWidth(), lblImagen.getHeight(),
                Image.SCALE_SMOOTH
            );
            lblImagen.setIcon(new ImageIcon(img));
        }
    }
}
    

    private void cargarDatos() {
        // Simulación temporal
        String tituloLibro = "El Principito";
        String solicitante = "Juan Pérez";
        String fechaSolicitud = "2025-11-04";
        String fechaDevolucion = "2025-11-11";
        String rutaImagen = "C:/biblioteca/imagenes/elprincipito.jpg";

        lblTitulo.setText(tituloLibro);
        jSolicitanteField1.setText(solicitante);
        jFechaSolitudField1.setText(fechaSolicitud);
        jFechaDevolucionField1.setText(fechaDevolucion);

        try {
            ImageIcon icon = new ImageIcon(rutaImagen);
            java.awt.Image img = icon.getImage().getScaledInstance(120, 150, java.awt.Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            lblImagen.setText("Sin imagen");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jSolicitanteField1 = new javax.swing.JTextField();
        jFechaSolitudField1 = new javax.swing.JTextField();
        jFechaDevolucionField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnConfirmarPrestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Titulo");

        jSolicitanteField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSolicitanteField1ActionPerformed(evt);
            }
        });

        jFechaSolitudField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFechaSolitudField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Confirmar Prestamo");

        jLabel2.setText("Solicitante");

        jLabel3.setText("Fecha de Solicitud");

        jLabel4.setText("Fecha de devolucion");

        btnConfirmarPrestamo.setText("Confirmar Prestamo");
        btnConfirmarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jSolicitanteField1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(jFechaSolitudField1)
                                    .addComponent(jFechaDevolucionField1)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnConfirmarPrestamo)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSolicitanteField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFechaSolitudField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFechaDevolucionField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnConfirmarPrestamo)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSolicitanteField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSolicitanteField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSolicitanteField1ActionPerformed

    private void jFechaSolitudField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFechaSolitudField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFechaSolitudField1ActionPerformed

    private void btnConfirmarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPrestamoActionPerformed
    PrestamoController pc = new PrestamoController();
    boolean exito = pc.registrarPrestamo(idUsuario, idLibro);

    if (exito) {
        JOptionPane.showMessageDialog(this,
            "Préstamo confirmado\nLibro: " + lblTitulo.getText());

        dispose(); // ahora SÍ se cerrará solo esta ventana
    } else {
        JOptionPane.showMessageDialog(this, 
            "Error al registrar el préstamo",
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfirmarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPrestamo;
    private javax.swing.JTextField jFechaDevolucionField1;
    private javax.swing.JTextField jFechaSolitudField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jSolicitanteField1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
